### ISSUE TITLE
[ISSUE] Azure ADAL Mount always detects diff due to extra slash

### ISSUE THREAD

**Issue by lawrencegripper** [databrickslabs/databricks-terraform#38]
Hi, 

A  bug we've hit that I'd like to pickup and PR a fix, looks like a super easy fix. We'd use integration tests to be added in #37 to validate it behaves correctly. 

When re-running the `adls_gen2_mount` resource it will always detect a change due to an additional slash being detected.

Think this is likely a 1 or 2 char change to fix then adding the tests to validate. 

### Terraform Version
```
# tf -v
Terraform v0.12.16
+ provider.azuread v0.8.0
+ provider.azurerm v2.8.0
+ provider.databricks v0.1.0
+ provider.random v2.2.1
```

### Affected Resource(s)

- databricks_azure_adls_gen2_mount

### Terraform Configuration Files
```hcl
resource "databricks_azure_adls_gen2_mount" "mount" {
  cluster_id           = databricks_cluster.cluster.id
  container_name       = "dev" #todo: replace with env...
  storage_account_name = azurerm_storage_account.account.name
  directory            = "/dir"
  mount_name           = "localdir"
  tenant_id            = data.azuread_client_config.current.tenant_id
  client_id            = azuread_application.datalake.application_id
  client_secret_scope  = databricks_secret_scope.terraform.name
  client_secret_key    = databricks_secret.client_secret.key
}
```

### Debug Output

```
> TF_LOG=debug tf plan -var-file vars.tfvars 2>&1 >/dev/null | grep "plugin.terraform-provider-databricks_v0.1.0"

2020-05-05T15:10:42.867Z [DEBUG] plugin.terraform-provider-databricks_v0.1.0: 2020/05/05 15:10:42 {"Method":"POST","URI":"https://eastus.azuredatabricks.net/api/1.2/commands/execute","Payload":{"language":"python","clusterId":"0504-155102-pram660","contextId":"2178625329361652192","command":"\ntry:\n  configs = {\"fs.azure.account.auth.type\": \"OAuth\",\n           \"fs.azure.account.oauth.provider.type\": \"org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider\",\n           \"fs.azure.account.oauth2.client.id\": \"REDACTED",\n           \"fs.azure.account.oauth2.client.secret\": dbutils.secrets.get(scope = \"terraform\", key = \"datalake_sp_secret\"),\n           \"fs.azure.account.oauth2.client.endpoint\": \"https://login.microsoftonline.com/REDACTED/oauth2/token\"}\n  dbutils.fs.mount(\n   source = \"abfss://dev@SOMESTORAGE.dfs.core.windows.net//dir\",\n   mount_point = \"/mnt/localdir\",\n   extra_configs = configs)\nexcept Exception as e:\n  dbutils.fs.unmount(\"/mnt/localdir\")\n  raise e\ndbutils.notebook.

```

### Expected Behavior

No diff should be found and plan should be empty.

### Actual Behavior

After first `apply` all `plan`/`apply` operations detect a `diff` and recreate the `mount`. 

![image](https://user-images.githubusercontent.com/1939288/81080649-e3957080-8ee8-11ea-9f3c-95daaa53e193.png)

This is due to the added `/` character 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
1. Do no changes to the mount in TF or in the cluster
2. `terraform plan`
2. Observe diff in plan due to additional slash on `directory` field

**Comment by stikkireddy** [comment]
Hey thank you very much @lawrencegripper please feel free to make a PR 😄 !

**Comment by stikkireddy** [comment]
@lawrencegripper FYI: I was just browsing through why this was occurring only for adls gen 2 and not gen 1 or abs, noticed that this occurs because of the formatting for the source url which has a "/" which shouldn't be there: 

Below is the adls gen 2 mount which has the abfss uri take a look at the source.
https://github.com/databrickslabs/databricks-terraform/blob/694b808e045fc86a71c7336bbd7c5dd70a0ae307/databricks/mounts.go#L308-L324

Now look at the source for the abs wasbs uri take a look at the source:
https://github.com/databrickslabs/databricks-terraform/blob/694b808e045fc86a71c7336bbd7c5dd70a0ae307/databricks/mounts.go#L120-L129

**Comment by lawrencegripper** [comment]
Nice, yup that looks like it's all that is needed to fix this one up. I'll make the change this morning then wrap in an integration test to prove it out.

**Comment by stikkireddy** [comment]
Going to close this issue as the PR is merged!
