### ISSUE TITLE
[FEATURE] Add Visual Studio Code Devcontainer support

### ISSUE THREAD

**Issue by stuartleeks** [databrickslabs/databricks-terraform#39]
**Is your feature request related to a problem? Please describe.**
I work across a bunch of repos and each has their own requirements for tooling (and tooling versions). As part of working on the issues that @lawrencegripper recently raised, we will create a VS Code Devcontainer definition. This allows us to capture and share the requirements in a container definition and use that for any work on the project. 

More information here: https://code.visualstudio.com/docs/remote/containers

**Describe the solution you'd like**
Contribute our `.devcontainer` folder with the definition of the container to use when working with VS Code Devcontainers for this repo so that others can use it if they choose that workflow.

**Comment by stuartleeks** [comment]
For context, this would be the addition: https://github.com/stuartleeks/databricks-terraform/tree/sl/devcontainer/.devcontainer

**Comment by stikkireddy** [comment]
Hey @stuartleeks this is a great idea, if possible can you also add a bit of documentation on how a user can use this. Unfortunately I am not too familiar with devcontainer. It can also be a link to vscode documentation if possible.

**Comment by stuartleeks** [comment]
@stikkireddy sounds good. I'll add a note to the README next to the prerequisites for getting started with VS Code devcontainers. Hope to have a PR for you this morning :-D
