### ISSUE TITLE
[FEATURE] Support for Azure AD credentials passthrough

### ISSUE THREAD

**Issue by mikemowgli** [databrickslabs/databricks-terraform#58]
In the `databricks_cluster` resource, it'd be nice to be able to enable Azure AD credentials passthrough.

**Comment by stikkireddy** [comment]
Hey @mikemowgli this is already part of the `databricks_cluster` resource. When you click enable azure ad credentials passthrough all databricks is doing is creating a spark conf item. To use in the cluster resource you can do the following:
https://databrickslabs.github.io/databricks-terraform/resources/cluster/#--spark_conf

```hcl

resource "databricks_cluster" "my_cluster" {
....
spark_conf = {
     "spark.databricks.passthrough.enabled": "true"
}
....
}
```

The same logic applies for table acls. 
Please let me know if this does not fully respond to your enhancement request.

**Comment by mikemowgli** [comment]
Didn't know it could be done via spark conf. Let's close it then. Thanks!
