### ISSUE TITLE
Problem initializing provider for MWS

### ISSUE THREAD

**Issue by psg2** [databrickslabs/databricks-terraform#93]
During configuration, there is validation to check if the host or token is empty and if one of them is, the provider will try to read the databricks config file.

```
		if config.Host == "" || config.Token == "" {
			if err := tryDatabricksCliConfigFile(d, &config); err != nil {
				return nil, fmt.Errorf("failed to get credentials from config file; error msg: %w", err)
			}
		}
```

The problem here is that for MWS you need to setup host and basic_auth, but if you don't provide token it will try to read your config file leading to two possible scenarios:
- It reads the file successfully and overwrites the host, to one that isn't the correct one set on the provider configuration
- It fails to read the file and doesn't continue the process to use basic_auth, quitting the provider's initialization.

You also can't use a placeholder token to avoid the usage of the config file, because token conflicts with basich_auth. Meaning that you need to create a config file or add a new profile to it, just to put the correct host that you specified in the .tf file initially.

Reference: https://github.com/databrickslabs/databricks-terraform/blob/b8b4d864175db4084c25e5a0ad072805caf6922d/databricks/provider.go#L298

Workaround:

```
provider "databricks" {
  host    = "https://accounts.cloud.databricks.com"
  profile = "ACCOUNT"
  basic_auth {
    username = "username"
    password = "password"
  }
}
```

```
[DEFAULT]
...

[ACCOUNT]
host = https://accounts.cloud.databricks.com
token = placeholder
```

**Comment by stikkireddy** [comment]
@psg2 sorry small oversight in terms of order of preference, it should be host + (token | basic auth) -> credentials file

**Comment by psg2** [comment]
No problem at all.
The next time if I have time I will try to collaborate with a pull request as well instead of just reporting. 😄
